### YamlMime:FAQ
metadata:
  title: Sık sorulan güvenlik soruları
  description: Karma gerçeklik cihazları hakkında sık sorulan güvenlik sorularını ve yanıtlarını HoloLens takip edin.
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: b09670ee24139c129629d061edae4d5bb43b2d766c90df152aeddb202cc1fe55
  ms.sourcegitcommit: f8e7cc2fbdcdf8962700fd50b9c017bd83d1ad65
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 08/05/2021
  ms.locfileid: "115662654"
title: Sık sorulan HoloLens (1. nesil) Güvenlik Soruları
summary: ''
sections:
- name: Yoksayıldı
  questions:
  - question: >
      1. veri HoloLens koruma düzeyi nedir?
    answer: >
      * Bkz. [HoloLens (1. Nesil) BitLocker Şifrelemesi](hololens1-encryption.md)
  - question: >
      Ne tür bir kablosuz ağ kullanılır?
    answer: >
      * 802.11ac ve Bluetooth 4.1 LE
  - question: >
      Ne tür bir mimariye dahil edilmiştir?  Örneğin: noktadan noktaya mı, örgüye mi yoksa başka bir şeye mi?
    answer: >
      * Wi-Fi, diğer kablosuz erişim noktalarıyla iletişim kurmak için altyapı modunda kullanılabilir.

      * Bluetooth, müşterilerin uygulaması destekliyorsa birden çok HoloLens eşler arasında eşler arası iletişim için veya diğer Bluetooth kullanılabilir.
  - question: >
      FCC KIMLIĞI nedir?
    answer: >
      * C3K1688
  - question: >
      Cihaz hangi sıklıkta ve kanallarda çalışır ve yapılandırılabilir?
    answer: >
      * Wi-Fi: Sıklık aralığı kullanıcı tarafından yapılandırılabilir değildir ve kullanım ülkeye bağlıdır. ABD Wi-Fi 2,4 GHz (1-11) kanal ve 5 GHz (36-64, 100-165) kanalları kullanır.

      * Bluetooth: Bluetooth 2,4-2,48 GHz aralığını kullanır.
  - question: >
      Cihaz belirli sıklıklara izin verir veya bu sıklıkları engelleyebilir mi?
    answer: >
      * Bu, kullanıcı/cihaz tarafından kontrol edilemez.
  - question: >
      Hem iletme hem de alma için güç düzeyi nedir? Ayarlanabilir mi? İşlem aralığı nedir?
    answer: >
      * Emisyon testi standartlarımız burada [bulunabilir.](https://fccid.io/C3K1688) İşlem aralığı erişim noktasına ve ortama yüksek oranda bağımlıdır, ancak kabaca diğer yüksek kaliteli telefonlara, tabletlere veya bilgisayarlara eşdeğerdir.
  - question: >
      Normal işlem için görev döngüsü/yaşam süresi nedir?
    answer: >
      * 2-3 sa etkin kullanım ve iki haftaya kadar bekleme süresi

      * Pil ömrü kullanılamıyor.
  - question: >
      Bir araç aralıkta değilken iletme ve alma davranışı nedir?
    answer: >
      * HoloLens/alma, standart #A0 Bluetooth izler. Aralığın sonunda, girişin tamamen bağlantısı kesinceye kadar girişin zor olduğunu fark edersiniz, ancak aralıka geri döndükten sonra hızlı bir şekilde yeniden bağlanmanız gerekir.
  - question: >
      Bir metre kare başına dağıtım yoğunluğu nedir?
    answer: >
      * Bu, ağ altyapınıza bağlıdır.
  - question: >
      Cihaz, altyapıyı istemci olarak kullanabilir mi?
    answer: >
      * Yes
  - question: >
      Hangi protokol kullanılır?
    answer: >
      * HoloLens hiçbir özel protokol kullanmaz
  - question: >
      Işletim sistemi güncelleştirme sıklığı – HL için işletim sistemi güncelleştirmelerinin sıklığı nedir?  Ayarlanmış bir zamanlama var mı?  Microsoft gerektiğinde güvenlik düzeltme eklerini vb. yayımlar mı?
    answer: >
      * Microsoft, işletim sistemi güncelleştirmelerini HoloLens aynı işletim sistemi güncelleştirmeleri için olduğu gibi Windows 10. Normalde yılda iki ana güncelleştirme vardır: biri spring, biri düşüşte. HoloLens bir Windows olduğu için, güncelleştirme kavramı diğer tüm cihaz Windows aynıdır. Microsoft, güvenlik yamalarını gerektiğinde yayımlar ve diğer tüm cihazlarda yapılanla aynı Windows izler.
  - question: >
      Işletim sistemi sağlamlaştırma – OS'nin sağlamlaştırması için hangi seçenekler vardır?  Gereksiz uygulamaları veya hizmetleri kaldırabilir veya kapatabilirsiniz.
    answer: >
      * HoloLens akıllı telefon gibi davranır. Diğer modern cihaz cihazlarıyla Windows benzerdir. HoloLens MobileIron, Airwatch Microsoft Intune Soti gibi diğer Modern Cihaz Yönetimi Çözümleri tarafından yönetilebilir. Bu Yönetim Sistemlerinde, cihaza Güvenlik ilkeleri koymak ve cihazı sağlamlaştırabilirsiniz. Ayrıca, gerekirse gereksiz uygulamaları silme seçeneği de vardır.
  - question: >
      Yazılım uygulamaları nasıl yönetilir ve güncelleştirilir? Microsoft mağazasında bulunan uygulamalar için yüklenen uygulamaları ve uygulama güncelleştirme işlemini tanımlamak için hangi denetime sahip oluruz?
    answer: >
      * HoloLens uygulamaları yalnızca Windows alır. Uygulama Paketlerinin Kullanımı için geliştirilen yalnızca Appx Uygulama Paketleri HoloLens. Bunu, uygulamanın yanında Microsoft Store cihazın yanında küçük bir logoyla birlikte HoloLens edebilirsiniz. Mağaza uygulamalarının yönetimi üzerinde sahip olduğunuz tüm denetimler, uygulama yönetimi HoloLens. Resmi mağaza veya mağaza kavramını iş için kullanabilirsiniz. Uygulamalar yan yüklenebilir (uygulamayı bir Windows cihazına yüklemek için el ile yapılan işlem) veya uygulamalar gerektiğinde mağazadan otomatik olarak çekilebilecek şekilde bir MDM üzerinden yönetilebilir.
  - question: >
      Depolama için mağazada uygulama güncelleştirmelerinin sıklığı HoloLens?
    answer: >
      * Uygulama geliştirme ve çekme Microsoft Store aynı kavramı takip ettiyseniz, güncelleştirme döngüsü Uygulamanın geliştiricisi tarafından belirlenir. Mağazada güncelleştirme mekanizmasını denetlemeniz için gereken tüm yönetim seçenekleri HoloLens için de geçerlidir.
  - question: >
      Bu özellik için güvenli bir önyükleme özelliği HoloLens?
    answer: >
      * Yes
  - question: >
      Cihaz için çevresel desteği devre dışı bırakma veya bağlantısını kesme olanağı var mı?
    answer: >
      * Yes
  - question: >
      Cihazda bağlantı noktalarının kullanımını denetleme veya devre dışı bırakma olanağı var mı?
    answer: >
      * Bu HoloLens yalnızca iki bağlantı noktası içerir (biri kulaklıklar için, biri de bilgisayarlara ücretlendirmek veya bilgisayarlara bağlanmak için). İşlevsellik ve kurtarma nedenlerinden dolayı bağlantı noktasını devre dışı bırakama özelliği yok.
  - question: >
      Virüsten koruma, uç nokta algılama, IPS, uygulama denetimi izin listesi – Virüsten koruma, uç nokta algılama, IPS, uygulama denetimi izin listesi vb. çalıştırma olanağı.
    answer: >
      * Windows Holographic for Business (ticari paket), Akıllı Ekran'Windows Defender desteklemez. Bir virüsten koruma şirketi kendi uygulamasını oluşturmak ve Universal Windows Platform'da yayımlamaksa, bu şirket HoloLens. Şu anda hiçbir şirket bu işi HoloLens.

      * Uygulamalara izin verme, yalnızca belirli Enterprise seçililebilen Microsoft Enterprise Store kullanılarak mümkündür. Ayrıca, MDM aracılığıyla belirli uygulamaların çalıştırılamayacaklarını ve hatta cihazda görüleblerini kilitlersiniz.
  - question: >
      Uzun bir süre çevrimdışı olan cihazı güncelleştirene kadar cihazı prod network'den karantinaya alı musunuz?  Örn. Cihaz bir süre (altı ay) boyunca açık değil ve herhangi bir güncelleştirme, düzeltme eki vb. almış bir çekmecede duruyor.  Ağa katılmaya çalıştığında bayrağını ve ağa katılma şikayeti olmadan önce başka bir ağ üzerinde güncelleştirmeniz gerektiğini söylememiz gerekir.
    answer: >
      * Bu, altyapı düzeyinde bir MDM veya bir on-prem sunucusu tarafından yönetilmitir. Cihaz, belirtilen bir Güncelleştirme sürümünü karşılayamasa uyumlu değil olarak işaretlenir.
  - question: >
      Microsoft, ekran paylaşımı veya uzaktan destek için Microsoft'un cihaza bağlanmasına izin veren herhangi bir arka kapı veya hizmet erişimi içerir mi?
    answer: >
      * No
  - question: >
      Güvenilen iletişim için bir PKI sertifikası oluşturulurken, yalnızca o cihazda olduğunu, bu cihaza özgü olduğunu ve cihazın kimliğine bürünmek için dışarı aktarılamayacak veya kullanılamayacak şekilde sertifikanın cihazda üretilmelerini sağlariz. Bu durum HoloLens? Yoksa, olası bir risk azaltması var mı?
    answer: >-
      * SCEP için CSR, cihazın kendi üzerinde oluşturulur. Intune ve şirket içi SCEP bağlayıcısı, istemciye gönderilen bir zorluk dizesi ekip doğrular ve isteklerin güvenliğini sağlar.

      * Bu HoloLens (1. Nesil ve 2. Nesil) bir TPM modülüne sahip olduğu için bu sertifikalar TPM modülünde depolanır ve ayıklanamaz. Ayrıca, ayıklansa bile, farklı bir cihazda zorluk dizeleri doğrulanamadı ve sertifikalar/anahtar farklı cihazlarda kullanılamaz hale geldi.
